name: Github actions launcher
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/launcher.yaml'

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Test environments
        run: echo "hello world!"