name: Github actions launcher
on:
  push:
    paths:
      - '.github/workflows/launcher.yaml'
    branches:
      - master
      - main
      - develop
      - candidate

jobs:
  workflow1:
    runs-on: ubuntu-latest

    steps:
    - name: workflow1
      uses: actions/checkout@v3
      
    - name: Trigger workflow1
      uses: AfeefGalil/simple-java-maven-app/.github/workflows/build_maven.yaml@master