name: Github actions launcher
on:
  push:
    paths:
      - '.github/workflows/launcher.yaml'
    branches:
      - master
      - main
      - develop
      - candidate

jobs:
  workflow_launch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow1
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: afeefgalil
          repo: simple-java-maven-app
          github_token: ${{ secrets.GH_TOKEN }}
          workflow_file_name: build_maven.yaml
          ref: master
          # wait_workflow: true

      - name: Trigger workflow2
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: afeefgalil
          repo: simple-java-maven-app2
          github_token: ${{ secrets.GH_TOKEN }}
          workflow_file_name: build_maven.yaml
          ref: main
          # wait_workflow: true