name: Github actions launcher
on:
  push:
    paths:
      - '.github/workflows/launcher.yaml'
    branches:
      - master
      - main
      - develop
      - candidate

jobs:
  workflow1:
    uses: AfeefGalil/simple-java-maven-app/.github/workflows/build_maven.yaml@master