name: Github actions launcher
on:
  push:
    paths:
      - '.github/workflows/launcher.yaml'
    branches:
      - master
      - main
      - develop
      - candidate

jobs:
  workflow1:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow1
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: AfeefGalil
          repo: simple-java-maven-app
          github_token: ${{ secrets.GH_TOKEN }}
          github_user: afeefgalil
          workflow_file_name: build_maven.yaml
          ref: master
          trigger_workflow: true
          wait_workflow: true