name: Github actions launcher
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yaml'

jobs:
  build:
    runs-on: self-hosted
    outputs:
      image-name: ${{ steps.building.outputs.image-name }}

    steps:
      - name: building
        id: building
        run: echo "::set-output name=image-name::afeef-image"

  test:
    runs-on: self-hosted
    needs: [build]

    steps:
      - name: testing
        run: echo "testing"


  deploy_stg:
    needs: [build, test]
    uses: afeefgalil/gha-launcher/.github/workflows/stg.yaml@main
    with:
     image_name: ${{needs.build.outputs.image-name}}

  deploy_prod:
    needs: [build, test]
    uses: afeefgalil/gha-launcher/.github/workflows/prod.yaml@main
    with:
     image_name: ${{needs.build.outputs.image-name}}