name: Github actions launcher
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yaml'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: building
        run: echo "building"

  test:
    runs-on: self-hosted

    steps:
      - name: testing
        run: echo "testing"

  deploy_stg:
    runs-on: self-hosted
    needs: [build, test]

    steps:
      - name: deploy stg
        run: echo "deploy stg"

  deploy_prod:
    needs: [deploy_stg]
    uses: afeefgalil/gha-launcher/.github/workflows/prod.yaml@main