name: Manuall approval
on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/manuall_approval.yaml'

jobs:
  manuall_approval:
    runs-on: ubuntu-latest

    steps:
      - uses: trstringer/manual-approval@v1
        with:
          approvers: afeefgalil
          minimum-approvals: 1
          issue-title: "Deploying to prod"
          secret: ${{ github.GH_TOKEN }}

      - name: deploying production
        run: echo "deploying production"