name: Prod
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '.github/workflows/prod.yaml'
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        description: image name
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        required: true
        description: image name

jobs:
  deploy_prod:
    runs-on: self-hosted
    environment: production

    steps:
      - name: image
        run: echo ${{ inputs.image_name }}