name: Staging
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/stg.yaml'
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        description: image name
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        required: true
        description: image name

jobs:
  deploy_stg:
    runs-on: self-hosted

    steps:
      - name: image
        run: echo ${{ inputs.image_name }}