name: test2
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test2.yaml'

jobs:
  test2:
    runs-on: [self-hosted, linux, x64, test2]

    steps:
      - name: test2
        run: echo "test 2"