name: test1
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test1.yaml'

jobs:
  test1:
    runs-on: self-hosted

    steps:
      - name: test1
        run: echo "test 1"