name: test1
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test1.yaml'

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
      - name: ssh
        run: cat ${{ secrets.SSH_KEY }} | ssh -T git@github.com