name: test2
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test2.yaml'

jobs:
  test1:
    runs-on: [self-hosted]

    steps:
      - name: test2
        run: echo "test 2"

  test2:
    runs-on: [self-hosted]

    steps:
      - name: test2
        run: echo "test 2"