name: test1
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test1.yaml'

jobs:
  test1:
    runs-on: [self-hosted, linux, x64, test1]
  
    steps:
      - name: test1
        run: echo "test 1"